allowBuilds:
  esbuild: true
  lefthook: true
  unrs-resolver: false
  workerd: true
minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.71.1'
  - '@typescript-eslint/parser@8.71.1'
  - '@typescript-eslint/project-service@8.71.1'
  - '@typescript-eslint/scope-manager@8.71.1'
  - '@typescript-eslint/tsconfig-utils@8.71.1'
  - '@typescript-eslint/type-utils@8.71.1'
  - '@typescript-eslint/types@8.71.1'
  - '@typescript-eslint/typescript-estree@8.71.1'
  - '@typescript-eslint/utils@8.71.1'
  - '@typescript-eslint/visitor-keys@8.71.1'
  - lefthook-darwin-arm64@2.1.17
  - lefthook-darwin-x64@2.1.17
  - lefthook-freebsd-arm64@2.1.17
  - lefthook-freebsd-x64@2.1.17
  - lefthook-linux-arm64@2.1.17
  - lefthook-linux-x64@2.1.17
  - lefthook-openbsd-arm64@2.1.17
  - lefthook-openbsd-x64@2.1.17
  - lefthook-windows-arm64@2.1.17
  - lefthook-windows-x64@2.1.17
  - lefthook@2.1.17
  - typescript-eslint@8.71.1
